spring:
  application:
    name: cloud-chaos
  mvc:
    pathMatch:
      matching-strategy: ant_path_matcher
  profiles:  
    active: dev
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name:
    url: jdbc:mysql://127.0.0.1:3306/chaos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: admin
    password: root123
  flyway:
    enabled: true # 正式环境才开启
    clean-disabled: true # 禁用数据库清理
    encoding: UTF-8
    locations: classpath:/db/migration # 指定sql 脚本的路径
    # flyway 会在库中创建此名称元数据表，用于记录所有版本演化和状态
    # 同一个库不同项目可能冲突，每个项目一张表来记录
    table: fsh_${spring.application.name} #后缀指定为当前项目名称
    baseline-version: 1 # 基线版本默认开始序号 默认为 1
    baseline-on-migrate: true #  针对非空数据库是否默认调用基线版本,为空的话默认会调用基线版本
  redis:
    database: 0
    # Redis服务器地址 写你的ip
    host: 127.0.0.1
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制  类似于mysql的连接池
    jedis:
      pool:
        max-active: 200
    # 连接池最大阻塞等待时间（使用负值表示没有限制） 表示连接池的链接拿完了 现在去申请需要等待的时间
        max-wait: -1
    # 连接池中的最大空闲连接
        max-idle: 10
    # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒） 去链接redis服务端
        timeout: 6000
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Dao.xml,classpath:**/*Dao.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lmc.**.entity
  global-config:
    db-config:
      id-type: AUTO
      update-strategy: default
      table-underline: true
      capital-mode: false
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
server:
  port: 8882 # 监听端口
chaos:
  swagger:
    scan: com.lmc
